cli:
  baseCommand: [dvc-cc-agent]
  class: CommandLineTool
  cwlVersion: v1.0
  doc: some descriptions of the package...
  inputs:
    git_authentication_json:
      doc: 'A path to json file which contains the git authentication. This should include the keys: username. email and password.'
      inputBinding: {position: 0}
      type: File
    git_path_to_working_repository:
      doc: 'The git working directory. With this you can specify what the main git root is.'
      inputBinding: {position: 1}
      type: string
    git_working_repository_owner:
      doc: 'The name of the owner of the git repository which you want to execute.'
      inputBinding: {position: 2}
      type: string
    git_working_repository_name:
      doc: 'The git repository name.'
      inputBinding: {position: 3}
      type: string
    git_name_of_branch:
      doc: 'The source code jumps to this here defined git tag (with git checkout) and execute dvc repro there.'
      inputBinding: {position: 4}
      type: string
    dvc_authentication_json:
      doc: 'A path to json file which contains the dvc authentication. This should include the keys: username and password.'
      inputBinding: {position: 5}
      type: File
    dvc_servername:
      doc: 'The servername of the dvc directory.'
      inputBinding: {position: 6}
      type: string
    dvc_path_to_working_repository:
      doc: 'The directory that is used for the dvc script.'
      inputBinding: {position: 7}
      type: string
    dvc_data_dir:
      doc: 'This is optional parameter. Here you can specify a sshfs folder for the "data" folder.'
      inputBinding: {prefix: --data_dir}
      type: Directory?
    dvc_remote_directory_sshfs:
      doc: 'A SSHFS connection to stream the output of DVC REPRO -P.'
      inputBinding: {prefix: --dvc_remote_directory_sshfs}
      type: Directory?
    dvc_file_to_execute:
      doc: 'This is optional parameter. If this parameter is given it will run "dvc repro DVC_FILE_TO_EXECUTE". Is this parameter is not set it will run "dvc repro -P"'
      inputBinding: {prefix: --dvc_file_to_execute}
      type: string?
    live_output_files:
      doc: 'Comma separated string list of files that should be included to the live output for example: tensorboard,output.json This could track a tensorboard folder and a output.json file.'
      inputBinding: {prefix: --live_output_files}
      type: string?
    live_output_update_frequence:
      doc: 'The update frequence of the live output in seconds.'
      inputBinding: {prefix: --live_output_update_frequence}
      type: int?
  outputs: {}
container:
  engine: docker
  settings:
    gpus:
      count: 1
      vendor: "nvidia"
    image:
      url: 'docker.io/deepprojects/dvc-cc_large:dev'
    ram: 20000
execution:
  engine: ccagency
  settings:
    access:
      auth: {password: '{{agency_password}}', username: '{{agency_username}}'}
      url: https://agency.f4.htw-berlin.de/dt
    batchConcurrencyLimit: 12
    retryIfFailed: false
redVersion: '8'
